export const ADD_STAFF = "ADD_STAFF";
export const STAFF_LOADING = "STAFF_LOADING";
export const STAFF_FAILED = "STAFF_FAILED";

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DEPARTMENT_LOADING = "DEPARTMENT_LOADING";
export const DEPARTMENT_FAILED = "DEPARTMENT_FAILED";
