export const ADD_STAFF = "ADD_STAFF";
export const STAFF_LOADING = "STAFF_LOADING";
export const STAFF_FAILED = "STAFF_FAILED";

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DEPARTMENT_LOADING = "DEPARTMENT_LOADING";
export const DEPARTMENT_FAILED = "DEPARTMENT_FAILED";

export const ADD_MONEY = "ADD_MONEY";
export const MONEY_LOADING = "MONEY_LOADING";
export const MONEY_FAILED = "MONEY_FAILED";

export const ADD_DEPARTMENT_STAFF = "ADD_DEPARTMENT_STAFF";
export const DEPARTMENT_STAFF_LOADING = "DEPARTMENT_STAFF_LOADING";
export const DEPARTMENT_STAFF_FAILED = "DEPARTMENT_STAFF_FAILED";

export const POST_STAFF = "POST_STAFF";
